services:
  app:
    container_name: backend
    image: hackathon_dw_2024
    build: ./Backend
    env_file: Backend/.env
    ports:
      - "8080:8080"
    networks:
      - docker-network
    volumes:
      - data:/var/lib/app/data
  pg_database:
    container_name: pg_database
    image: hackathon_dw_2024_db
    build: ./Database
    env_file: Backend/.env
    ports:
      - "5432:5432"
    networks:
      - docker-network
    volumes:
      - data:/var/lib/postgresql/data
  frontend:
    container_name: frontend
    image: hackathon_dw_2024_fr
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge
volumes:
  data: